---
- hosts: at01
  tasks:
    - name: Get host name
      shell: hostname
      register: machine_name
    - debug:
        var: machine_name.stdout
    - name: check if entry already presented
      shell: cat /etc/hosts |grep {{ansible_ssh_connection}}
      register: entry_check
      ignore_errors: true
      
    - debug:
        var: entry_check.stdout
        
